source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!
platform :ios, '11.0'

target 'YQFMDB_Example' do
  pod 'YQFMDB', :path => '../'

  target 'YQFMDB_Tests' do
    inherit! :search_paths

    
  end
end
